export const DUMMY_ANALYTICS = {
	overview: {
		total_active_shipments: 4,
		critical_count: 1,
		high_risk_count: 1,
		medium_risk_count: 1,
		low_risk_count: 1,
		on_time_percentage: 86.4,
		delayed_count: 2,
		rerouted_this_week: 3,
		total_value_monitored_usd: 4620000,
		financial_losses_prevented_usd: 183000,
	},
	accuracy: {
		overall_model_accuracy: 88.4,
		xgboost_rmse: 4.2,
		xgboost_r2: 0.91,
		random_forest_delay_mae: 1.8,
		gradient_boost_accuracy: 94.1,
		total_predictions_made: 3287,
		correct_reroute_decisions: 41,
		incorrect_reroute_decisions: 3,
	},
	risk_history_7_days: [
		{ date: 'Jan 16', critical: 0, high: 2, medium: 3, low: 5 },
		{ date: 'Jan 17', critical: 1, high: 1, medium: 4, low: 4 },
		{ date: 'Jan 18', critical: 2, high: 2, medium: 2, low: 4 },
		{ date: 'Jan 19', critical: 1, high: 3, medium: 3, low: 3 },
		{ date: 'Jan 20', critical: 0, high: 1, medium: 4, low: 5 },
		{ date: 'Jan 21', critical: 1, high: 2, medium: 2, low: 5 },
		{ date: 'Jan 22', critical: 1, high: 1, medium: 1, low: 4 },
	],
};

export const DUMMY_PORTS = [
	{
		port_id: 'PORT-RTM',
		code: 'NLRTM',
		name: 'Rotterdam',
		country: 'Netherlands',
		lat: 51.9,
		lng: 4.5,
		status: 'severely_congested',
		vessels_in_queue: 47,
		avg_wait_hours: 38,
		port_score: 100,
	},
	{
		port_id: 'PORT-HHN',
		code: 'DEHAM',
		name: 'Hamburg',
		country: 'Germany',
		lat: 53.5,
		lng: 9.9,
		status: 'normal',
		vessels_in_queue: 4,
		avg_wait_hours: 3,
		port_score: 15,
	},
	{
		port_id: 'PORT-SGN',
		code: 'SGSIN',
		name: 'Singapore',
		country: 'Singapore',
		lat: 1.3,
		lng: 103.8,
		status: 'busy',
		vessels_in_queue: 12,
		avg_wait_hours: 8,
		port_score: 42,
	},
	{
		port_id: 'PORT-SHA',
		code: 'CNSHA',
		name: 'Shanghai',
		country: 'China',
		lat: 31.2,
		lng: 121.5,
		status: 'normal',
		vessels_in_queue: 6,
		avg_wait_hours: 4,
		port_score: 22,
	},
	{
		port_id: 'PORT-BUS',
		code: 'KRPUS',
		name: 'Busan',
		country: 'South Korea',
		lat: 35.1,
		lng: 129.0,
		status: 'normal',
		vessels_in_queue: 3,
		avg_wait_hours: 2,
		port_score: 12,
	},
	{
		port_id: 'PORT-LAX',
		code: 'USLAX',
		name: 'Los Angeles',
		country: 'USA',
		lat: 33.7,
		lng: -118.2,
		status: 'busy',
		vessels_in_queue: 9,
		avg_wait_hours: 6,
		port_score: 35,
	},
	{
		port_id: 'PORT-ANT',
		code: 'BEANR',
		name: 'Antwerp',
		country: 'Belgium',
		lat: 51.3,
		lng: 4.4,
		status: 'busy',
		vessels_in_queue: 11,
		avg_wait_hours: 9,
		port_score: 45,
	},
	{
		port_id: 'PORT-DXB',
		code: 'AEJEA',
		name: 'Jebel Ali',
		country: 'UAE',
		lat: 25.0,
		lng: 55.1,
		status: 'normal',
		vessels_in_queue: 5,
		avg_wait_hours: 3,
		port_score: 18,
	},
];
