export const DUMMY_SHIPMENTS = [
	{
		shipment_id: 'SHP-2025-00847',
		tracking_number: 'SAMS847KR2025',
		origin: 'Samsung Factory, Suwon, South Korea',
		destination: 'Amazon Warehouse, Berlin, Germany',
		cargo_type: 'Electronics',
		cargo_description: '500 Samsung Laptop Model X5',
		weight_kg: 2500,
		declared_value: 750000,
		priority: 'high',
		status: 'in_transit',
		current_risk_level: 'critical',
		current_risk_score: 91,
		is_rerouted: true,
		reroute_count: 1,
		departure_at: '2025-01-15T06:00:00Z',
		expected_arrival: '2025-02-12T10:00:00Z',
		actual_arrival: null,
		assigned_manager: 'Sarah Chen',
		assigned_vessel: 'MV Pacific Star',
		shipper_name: 'Kim Ji-ho',
		receiver_name: 'Anna Schmidt',
		current_coordinates: { lat: 32.5, lng: 152.8 },
		route_waypoints: [
			{ lat: 37.5, lng: 127.0 },
			{ lat: 35.1, lng: 129.0 },
			{ lat: 32.5, lng: 152.8 },
			{ lat: 51.9, lng: 4.5 },
			{ lat: 52.5, lng: 13.4 },
		],
	},
	{
		shipment_id: 'SHP-2025-00612',
		tracking_number: 'SGLT612EU2025',
		origin: 'Shenzhen Port, China',
		destination: 'Felixstowe Port, UK',
		cargo_type: 'Standard Dry',
		cargo_description: 'Consumer Electronics Components',
		weight_kg: 18000,
		declared_value: 320000,
		priority: 'medium',
		status: 'in_transit',
		current_risk_level: 'high',
		current_risk_score: 68,
		is_rerouted: false,
		reroute_count: 0,
		departure_at: '2025-01-10T08:00:00Z',
		expected_arrival: '2025-02-05T14:00:00Z',
		actual_arrival: null,
		assigned_manager: 'Sarah Chen',
		assigned_vessel: 'MV Global Trader',
		shipper_name: 'TechParts Ltd',
		receiver_name: 'UK Distribution Centre',
		current_coordinates: { lat: 12.5, lng: 44.2 },
		route_waypoints: [
			{ lat: 22.5, lng: 114.1 },
			{ lat: 12.5, lng: 44.2 },
			{ lat: 51.9, lng: 1.3 },
		],
	},
	{
		shipment_id: 'SHP-2025-00445',
		tracking_number: 'PHARM445US2025',
		origin: 'Mumbai Port, India',
		destination: 'Rotterdam Port, Netherlands',
		cargo_type: 'Pharmaceutical',
		cargo_description: 'Temperature-controlled vaccines',
		weight_kg: 800,
		declared_value: 2100000,
		priority: 'urgent',
		status: 'in_transit',
		current_risk_level: 'medium',
		current_risk_score: 44,
		is_rerouted: false,
		reroute_count: 0,
		departure_at: '2025-01-18T04:00:00Z',
		expected_arrival: '2025-02-08T09:00:00Z',
		actual_arrival: null,
		assigned_manager: 'Sarah Chen',
		assigned_vessel: 'MV Reefer Express',
		shipper_name: 'PharmaCo India',
		receiver_name: 'EuroHealth Distribution',
		current_coordinates: { lat: 14.2, lng: 53.1 },
		route_waypoints: [
			{ lat: 18.9, lng: 72.8 },
			{ lat: 14.2, lng: 53.1 },
			{ lat: 12.8, lng: 44.9 },
			{ lat: 51.9, lng: 4.5 },
		],
	},
	{
		shipment_id: 'SHP-2025-00231',
		tracking_number: 'AUTO231JP2025',
		origin: 'Yokohama Port, Japan',
		destination: 'Los Angeles Port, USA',
		cargo_type: 'Automotive',
		cargo_description: 'Toyota vehicle components',
		weight_kg: 35000,
		declared_value: 890000,
		priority: 'high',
		status: 'at_port',
		current_risk_level: 'low',
		current_risk_score: 18,
		is_rerouted: false,
		reroute_count: 0,
		departure_at: '2025-01-05T10:00:00Z',
		expected_arrival: '2025-01-29T16:00:00Z',
		actual_arrival: null,
		assigned_manager: 'Sarah Chen',
		assigned_vessel: 'MV Trans Pacific',
		shipper_name: 'Toyota Logistics',
		receiver_name: 'LA Auto Parts Hub',
		current_coordinates: { lat: 33.7, lng: -118.2 },
		route_waypoints: [
			{ lat: 35.4, lng: 139.6 },
			{ lat: 35.0, lng: -140.0 },
			{ lat: 33.7, lng: -118.2 },
		],
	},
	{
		shipment_id: 'SHP-2025-00178',
		tracking_number: 'FOOD178BR2025',
		origin: 'Santos Port, Brazil',
		destination: 'Hamburg Port, Germany',
		cargo_type: 'Perishable',
		cargo_description: 'Frozen beef 22 containers',
		weight_kg: 48000,
		declared_value: 560000,
		priority: 'high',
		status: 'delivered',
		current_risk_level: 'low',
		current_risk_score: 8,
		is_rerouted: false,
		reroute_count: 0,
		departure_at: '2024-12-20T06:00:00Z',
		expected_arrival: '2025-01-20T08:00:00Z',
		actual_arrival: '2025-01-19T14:00:00Z',
		assigned_manager: 'Sarah Chen',
		assigned_vessel: 'MV Cold Chain',
		shipper_name: 'BrazilFoods Export',
		receiver_name: 'Hamburg Cold Storage',
		current_coordinates: { lat: 53.5, lng: 9.9 },
		route_waypoints: [],
	},
];

export const DUMMY_ML_PREDICTION = {
	shipment_id: 'SHP-2025-00847',
	prediction_timestamp: new Date().toISOString(),
	input_features: {
		weather_score: 75,
		traffic_score: 30,
		port_score: 82,
		historical_score: 65,
		cargo_sensitivity: 65,
		distance_remaining_km: 9800,
		time_of_day: 14,
		day_of_week: 2,
		season: 1,
	},
	model_outputs: {
		xgboost_risk_score: 91,
		random_forest_delay_hours: 18.5,
		gradient_boost_reroute: true,
		gradient_boost_confidence: 92.3,
		lstm_trajectory: [91, 88, 84, 80, 76, 71],
	},
	feature_importance: {
		weather_score: 0.38,
		port_score: 0.29,
		traffic_score: 0.14,
		historical_score: 0.11,
		cargo_sensitivity: 0.08,
	},
	alternate_routes: [
		{
			route_id: 'RTE-00847-ALT1',
			name: 'Southern Pacific Route',
			description: 'Divert 800km south to avoid storm system',
			risk_score: 28,
			risk_level: 'low',
			delay_hours: 0.8,
			extra_distance_km: 800,
			extra_time_hours: 19,
			extra_cost_usd: 12000,
			optimization_score: 18.5,
			recommended: true,
		},
		{
			route_id: 'RTE-00847-ALT2',
			name: 'Guam Waypoint Route',
			description: 'Stop at Guam for 2 days until storm passes',
			risk_score: 18,
			risk_level: 'low',
			delay_hours: 48,
			extra_distance_km: 400,
			extra_time_hours: 52,
			extra_cost_usd: 35000,
			optimization_score: 42.1,
			recommended: false,
		},
		{
			route_id: 'RTE-00847-ALT3',
			name: 'Accelerated Direct Route',
			description: 'Increase speed to outrun storm front',
			risk_score: 79,
			risk_level: 'high',
			delay_hours: 6,
			extra_distance_km: 0,
			extra_time_hours: 0,
			extra_cost_usd: 8000,
			optimization_score: 55.7,
			recommended: false,
		},
	],
	financial_impact: {
		current_route_damage_probability: 0.34,
		current_route_expected_loss_usd: 255000,
		recommended_route_extra_cost_usd: 12000,
		recommended_route_expected_loss_usd: 60000,
		net_saving_usd: 183000,
	},
};
